/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MapRouteImport } from './routes/map'
import { Route as SegregatedRouteImport } from './routes/segregated'
import { Route as IncidentsIndexRouteImport } from './routes/incidents/index'
import { Route as IncidentsIncidentIdRouteImport } from './routes/incidents/$incidentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const SegregatedRoute = SegregatedRouteImport.update({
  id: '/segregated',
  path: '/segregated',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIndexRoute = IncidentsIndexRouteImport.update({
  id: '/incidents/',
  path: '/incidents/',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIncidentIdRoute = IncidentsIncidentIdRouteImport.update({
  id: '/incidents/$incidentId',
  path: '/incidents/$incidentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/segregated': typeof SegregatedRoute
  '/incidents/$incidentId': typeof IncidentsIncidentIdRoute
  '/incidents/': typeof IncidentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/segregated': typeof SegregatedRoute
  '/incidents/$incidentId': typeof IncidentsIncidentIdRoute
  '/incidents': typeof IncidentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/segregated': typeof SegregatedRoute
  '/incidents/$incidentId': typeof IncidentsIncidentIdRoute
  '/incidents/': typeof IncidentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/map' | '/segregated' | '/incidents/$incidentId' | '/incidents/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/map' | '/segregated' | '/incidents/$incidentId' | '/incidents'
  id:
    | '__root__'
    | '/'
    | '/map'
    | '/segregated'
    | '/incidents/$incidentId'
    | '/incidents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapRoute: typeof MapRoute
  SegregatedRoute: typeof SegregatedRoute
  IncidentsIncidentIdRoute: typeof IncidentsIncidentIdRoute
  IncidentsIndexRoute: typeof IncidentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segregated': {
      id: '/segregated'
      path: '/segregated'
      fullPath: '/segregated'
      preLoaderRoute: typeof SegregatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/': {
      id: '/incidents/'
      path: '/incidents'
      fullPath: '/incidents/'
      preLoaderRoute: typeof IncidentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/$incidentId': {
      id: '/incidents/$incidentId'
      path: '/incidents/$incidentId'
      fullPath: '/incidents/$incidentId'
      preLoaderRoute: typeof IncidentsIncidentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapRoute: MapRoute,
  SegregatedRoute: SegregatedRoute,
  IncidentsIncidentIdRoute: IncidentsIncidentIdRoute,
  IncidentsIndexRoute: IncidentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
